#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (0 << 8))
#define MAP_SLATEPORT_CITY      (1 | (0 << 8))
#define MAP_MAUVILLE_CITY       (2 | (0 << 8))
#define MAP_RUSTBORO_CITY       (3 | (0 << 8))
#define MAP_FORTREE_CITY        (4 | (0 << 8))
#define MAP_LILYCOVE_CITY       (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (0 << 8))
#define MAP_OLDALE_TOWN         (10 | (0 << 8))
#define MAP_DEWFORD_TOWN        (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (0 << 8))
#define MAP_ROUTE101            (16 | (0 << 8))
#define MAP_ROUTE102            (17 | (0 << 8))
#define MAP_ROUTE103            (18 | (0 << 8))
#define MAP_ROUTE104            (19 | (0 << 8))
#define MAP_ROUTE105            (20 | (0 << 8))
#define MAP_ROUTE106            (21 | (0 << 8))
#define MAP_ROUTE107            (22 | (0 << 8))
#define MAP_ROUTE108            (23 | (0 << 8))
#define MAP_ROUTE109            (24 | (0 << 8))
#define MAP_ROUTE110            (25 | (0 << 8))
#define MAP_ROUTE111            (26 | (0 << 8))
#define MAP_ROUTE112            (27 | (0 << 8))
#define MAP_ROUTE113            (28 | (0 << 8))
#define MAP_ROUTE114            (29 | (0 << 8))
#define MAP_ROUTE115            (30 | (0 << 8))
#define MAP_ROUTE116            (31 | (0 << 8))
#define MAP_ROUTE117            (32 | (0 << 8))
#define MAP_ROUTE118            (33 | (0 << 8))
#define MAP_ROUTE119            (34 | (0 << 8))
#define MAP_ROUTE120            (35 | (0 << 8))
#define MAP_ROUTE121            (36 | (0 << 8))
#define MAP_ROUTE122            (37 | (0 << 8))
#define MAP_ROUTE123            (38 | (0 << 8))
#define MAP_ROUTE124            (39 | (0 << 8))
#define MAP_ROUTE125            (40 | (0 << 8))
#define MAP_ROUTE126            (41 | (0 << 8))
#define MAP_ROUTE127            (42 | (0 << 8))
#define MAP_ROUTE128            (43 | (0 << 8))
#define MAP_ROUTE129            (44 | (0 << 8))
#define MAP_ROUTE130            (45 | (0 << 8))
#define MAP_ROUTE131            (46 | (0 << 8))
#define MAP_ROUTE132            (47 | (0 << 8))
#define MAP_ROUTE133            (48 | (0 << 8))
#define MAP_ROUTE134            (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (0 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (3 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (3 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (3 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (3 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (4 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (8 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (8 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (8 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (9 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (9 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (9 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (9 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (9 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (9 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (10 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (10 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (10 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (11 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (11 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (11 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (11 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (12 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (12 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (12 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (13 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (13 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (13 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (13 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (13 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (14 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (15 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (17 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (17 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (18 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (18 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (19 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (19 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (20 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (20 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (20 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (21 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (22 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (23 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (24 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (24 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (24 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (24 << 8))
#define MAP_DESERT_RUINS                             (6 | (24 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (24 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (24 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (24 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (24 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (24 << 8))
#define MAP_MT_CHIMNEY                               (12 | (24 << 8))
#define MAP_JAGGED_PASS                              (13 | (24 << 8))
#define MAP_FIERY_PATH                               (14 | (24 << 8))
#define MAP_MT_PYRE_1F                               (15 | (24 << 8))
#define MAP_MT_PYRE_2F                               (16 | (24 << 8))
#define MAP_MT_PYRE_3F                               (17 | (24 << 8))
#define MAP_MT_PYRE_4F                               (18 | (24 << 8))
#define MAP_MT_PYRE_5F                               (19 | (24 << 8))
#define MAP_MT_PYRE_6F                               (20 | (24 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (24 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (24 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (24 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (24 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (24 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (24 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (24 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (24 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (24 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (24 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (24 << 8))
#define MAP_ISLAND_CAVE                              (67 | (24 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (24 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (24 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (24 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (24 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (24 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (24 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (24 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (24 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (24 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (24 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (24 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (24 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (24 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (24 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (24 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (24 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (24 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (24 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (24 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (24 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (24 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (24 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (24 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (24 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (24 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (24 << 8))
#define MAP_ALTERING_CAVE                            (106 | (24 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (24 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (25 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (25 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (25 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (25 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (25 << 8))
#define MAP_TRADE_CENTER             (25 | (25 << 8))
#define MAP_RECORD_CORNER            (26 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (25 << 8))
#define MAP_CONTEST_HALL             (28 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (25 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (25 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (25 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (25 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (25 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (25 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (25 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (25 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (25 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (25 << 8))
#define MAP_UNION_ROOM               (60 | (25 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (26 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (26 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (26 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (26 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (26 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (26 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (26 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (26 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (26 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (26 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (26 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (26 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (26 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (26 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (26 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (26 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (26 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (26 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (26 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (26 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (26 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (26 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (26 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (26 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (26 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (26 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (26 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (27 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (27 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (28 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (29 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (30 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (31 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (32 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (32 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (32 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (33 << 8))

// gMapGroup_PalletTown
#define MAP_PALLET_TOWN        (0 | (34 << 8))
#define MAP_PLAYERS_HOUSE_1F   (1 | (34 << 8))
#define MAP_PLAYERS_HOUSE_2F   (2 | (34 << 8))
#define MAP_GARYS_HOUSE        (3 | (34 << 8))
#define MAP_PROFESSOR_OAKS_LAB (4 | (34 << 8))

// gMapGroup_ViridianCity
#define MAP_VIRIDIAN_CITY                   (0 | (35 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE1            (1 | (35 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (2 | (35 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE2            (3 | (35 << 8))
#define MAP_VIRIDIAN_CITY_MART              (4 | (35 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (5 | (35 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (6 | (35 << 8))

// gMapGroup_PewterCity
#define MAP_PEWTER_CITY                   (0 | (36 << 8))
#define MAP_PEWTER_CITY_MUSEUM_1F         (1 | (36 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (2 | (36 << 8))
#define MAP_PEWTER_CITY_GYM               (3 | (36 << 8))
#define MAP_PEWTER_CITY_MART              (4 | (36 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (5 | (36 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (6 | (36 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (7 | (36 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (8 | (36 << 8))

// gMapGroup_CeruleanCity
#define MAP_CERULEAN_CITY                   (0 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE1            (1 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (2 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (3 | (37 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (4 | (37 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F (5 | (37 << 8))
#define MAP_CERULEAN_CITY_GYM               (6 | (37 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (7 | (37 << 8))
#define MAP_CERULEAN_CITY_MART              (8 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (9 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (10 | (37 << 8))
#define MAP_CERULEAN_CAVE_1F                (11 | (37 << 8))
#define MAP_CERULEAN_CAVE_2F                (12 | (37 << 8))
#define MAP_CERULEAN_CAVE_B1F               (13 | (37 << 8))

// gMapGroup_LavenderTown
#define MAP_LAVENDER_TOWN                         (0 | (38 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F       (1 | (38 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F       (2 | (38 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE (3 | (38 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1                  (4 | (38 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2                  (5 | (38 << 8))
#define MAP_LAVENDER_TOWN_MART                    (6 | (38 << 8))
#define MAP_POKEMON_TOWER_1F                      (7 | (38 << 8))
#define MAP_POKEMON_TOWER_2F                      (8 | (38 << 8))
#define MAP_POKEMON_TOWER_3F                      (9 | (38 << 8))
#define MAP_POKEMON_TOWER_4F                      (10 | (38 << 8))
#define MAP_POKEMON_TOWER_5F                      (11 | (38 << 8))
#define MAP_POKEMON_TOWER_6F                      (12 | (38 << 8))
#define MAP_POKEMON_TOWER_7F                      (13 | (38 << 8))

// gMapGroup_VermilionCity
#define MAP_VERMILION_CITY                   (0 | (39 << 8))
#define MAP_VERMILION_CITY_HOUSE1            (1 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (2 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F (3 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB  (4 | (39 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (5 | (39 << 8))
#define MAP_VERMILION_CITY_MART              (6 | (39 << 8))
#define MAP_VERMILION_CITY_GYM               (7 | (39 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (8 | (39 << 8))
#define MAP_SSANNE_EXTERIOR                  (9 | (39 << 8))

// gMapGroup_CeladonCity
#define MAP_CELADON_CITY                           (0 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (1 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (2 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (3 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (4 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (5 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF     (6 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (7 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_1F           (8 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_2F           (9 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_3F           (10 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF         (11 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM    (12 | (40 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (13 | (40 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (14 | (40 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (15 | (40 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (16 | (40 << 8))
#define MAP_ROCKET_HIDEOUT_B1F                     (17 | (40 << 8))
#define MAP_ROCKET_HIDEOUT_B2F                     (18 | (40 << 8))
#define MAP_ROCKET_HIDEOUT_B3F                     (19 | (40 << 8))
#define MAP_ROCKET_HIDEOUT_B4F                     (20 | (40 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR                (21 | (40 << 8))
#define MAP_CELADON_CITY_GYM                       (22 | (40 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (23 | (40 << 8))
#define MAP_CELADON_CITY_HOUSE1                    (24 | (40 << 8))
#define MAP_CELADON_CITY_HOTEL                     (25 | (40 << 8))

// gMapGroup_FuchsiaCity
#define MAP_FUCHSIA_CITY                      (0 | (41 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE (1 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_CENTER          (2 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_EAST            (3 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_NORTH           (4 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_WEST            (5 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_BUILDING1       (6 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_BUILDING2       (7 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_BUILDING3       (8 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_BUILDING4       (9 | (41 << 8))
#define MAP_KANTO_SAFARI_ZONE_SECRET_HOUSE    (10 | (41 << 8))
#define MAP_FUCHSIA_CITY_MART                 (11 | (41 << 8))
#define MAP_FUCHSIA_CITY_ZOO_BUILDING         (12 | (41 << 8))
#define MAP_FUCHSIA_CITY_GYM                  (13 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1               (14 | (41 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F    (15 | (41 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F    (16 | (41 << 8))
#define MAP_FUCHSIA_CITY_BUILDING1            (17 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2               (18 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3               (19 | (41 << 8))

// gMapGroup_CinnabarIsland
#define MAP_NEW_MAP1                          (0 | (42 << 8))
#define MAP_CINNABAR_ISLAND_GYM               (1 | (42 << 8))
#define MAP_POKEMON_LAB_ENTRANCE              (2 | (42 << 8))
#define MAP_POKEMON_LAB_LOUNGE                (3 | (42 << 8))
#define MAP_POKEMON_LAB_RESEARCH_ROOM         (4 | (42 << 8))
#define MAP_POKEMON_LAB_EXPERIMENT_ROOM       (5 | (42 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (6 | (42 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F (7 | (42 << 8))
#define MAP_CINNABAR_ISLAND_MART              (8 | (42 << 8))
#define MAP_POKEMON_MANSION_1F                (9 | (42 << 8))
#define MAP_POKEMON_MANSION_2F                (10 | (42 << 8))
#define MAP_POKEMON_MANSION_3F                (11 | (42 << 8))
#define MAP_POKEMON_MANSION_B1F               (12 | (42 << 8))

// gMapGroup_SaffronCity
#define MAP_SAFFRON_CITY                          (0 | (43 << 8))
#define MAP_SAFFRON_CITY_CLASSIC                  (1 | (43 << 8))
#define MAP_SAFFRON_CITY_HOUSE1_1F                (2 | (43 << 8))
#define MAP_SAFFRON_CITY_HOUSE1_2F                (3 | (43 << 8))
#define MAP_SAFFRON_CITY_DOJO                     (4 | (43 << 8))
#define MAP_SAFFRON_CITY_GYM                      (5 | (43 << 8))
#define MAP_SAFFRON_CITY_HOUSE2                   (6 | (43 << 8))
#define MAP_SAFFRON_CITY_MART                     (7 | (43 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F        (8 | (43 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F        (9 | (43 << 8))
#define MAP_SAFFRON_CITY_HOUSE3                   (10 | (43 << 8))
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB (11 | (43 << 8))
#define MAP_SILPH_CO_1F                           (12 | (43 << 8))
#define MAP_SILPH_CO_2F                           (13 | (43 << 8))
#define MAP_SILPH_CO_3F                           (14 | (43 << 8))
#define MAP_SILPH_CO_4F                           (15 | (43 << 8))
#define MAP_SILPH_CO_5F                           (16 | (43 << 8))
#define MAP_SILPH_CO_6F                           (17 | (43 << 8))
#define MAP_SILPH_CO_7F                           (18 | (43 << 8))
#define MAP_SAFFRON_CITY_8F                       (19 | (43 << 8))
#define MAP_SILPH_CO_9F                           (20 | (43 << 8))
#define MAP_SILPH_CO_10F                          (21 | (43 << 8))
#define MAP_SILPH_CO_11F                          (22 | (43 << 8))
#define MAP_SILPH_CO_ELEVATOR                     (23 | (43 << 8))

// gMapGroup_IndigoPlateau
#define MAP_INDIGO_PLATEAU_EXTERIOR             (0 | (44 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F    (1 | (44 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F    (2 | (44 << 8))
#define MAP_KANTO_POKEMON_LEAGUE_LORELEIS_ROOM  (3 | (44 << 8))
#define MAP_KANTO_POKEMON_LEAGUE_BRUNOS_ROOM    (4 | (44 << 8))
#define MAP_POKEMON_LEAGUE_AGATHAS_ROOM         (5 | (44 << 8))
#define MAP_KANTO_POKEMON_LEAGUE_LANCES_ROOM    (6 | (44 << 8))
#define MAP_KANTO_POKEMON_LEAGUE_CHAMPIONS_ROOM (7 | (44 << 8))
#define MAP_KANTO_POKEMON_LEAGUE_HALL_OF_FAME   (8 | (44 << 8))

// gMapGroup_KantoRoutes
#define MAP_ROUTE1                                (0 | (45 << 8))
#define MAP_ROUTE2                                (1 | (45 << 8))
#define MAP_ROUTE3                                (2 | (45 << 8))
#define MAP_ROUTE4                                (3 | (45 << 8))
#define MAP_ROUTE5                                (4 | (45 << 8))
#define MAP_ROUTE6                                (5 | (45 << 8))
#define MAP_ROUTE7                                (6 | (45 << 8))
#define MAP_ROUTE8                                (7 | (45 << 8))
#define MAP_ROUTE9                                (8 | (45 << 8))
#define MAP_ROUTE10                               (9 | (45 << 8))
#define MAP_ROUTE11                               (10 | (45 << 8))
#define MAP_ROUTE12                               (11 | (45 << 8))
#define MAP_ROUTE13                               (12 | (45 << 8))
#define MAP_ROUTE14                               (13 | (45 << 8))
#define MAP_ROUTE15                               (14 | (45 << 8))
#define MAP_ROUTE16                               (15 | (45 << 8))
#define MAP_ROUTE17                               (16 | (45 << 8))
#define MAP_ROUTE18                               (17 | (45 << 8))
#define MAP_ROUTE19                               (18 | (45 << 8))
#define MAP_ROUTE20                               (19 | (45 << 8))
#define MAP_ROUTE21_NORTH                         (20 | (45 << 8))
#define MAP_ROUTE21_SOUTH                         (21 | (45 << 8))
#define MAP_ROUTE22                               (22 | (45 << 8))
#define MAP_ROUTE23                               (23 | (45 << 8))
#define MAP_ROUTE24                               (24 | (45 << 8))
#define MAP_ROUTE25                               (25 | (45 << 8))
#define MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE (26 | (45 << 8))
#define MAP_ROUTE2_HOUSE                          (27 | (45 << 8))
#define MAP_ROUTE2_EAST_BUILDING                  (28 | (45 << 8))
#define MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE (29 | (45 << 8))
#define MAP_VIRIDIAN_FOREST                       (30 | (45 << 8))
#define MAP_DIGLETTS_CAVE_NORTH_ENTRANCE          (31 | (45 << 8))
#define MAP_DIGLETTS_CAVE                         (32 | (45 << 8))
#define MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE          (33 | (45 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_1F              (34 | (45 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_2F              (35 | (45 << 8))
#define MAP_MT_MOON_1F                            (36 | (45 << 8))
#define MAP_MT_MOON_B1F                           (37 | (45 << 8))
#define MAP_MT_MOON_B2F                           (38 | (45 << 8))
#define MAP_ROUTE5_POKEMON_DAY_CARE               (39 | (45 << 8))
#define MAP_ROUTE5_SOUTH_ENTRANCE                 (40 | (45 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_ENTRANCE       (41 | (45 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL   (42 | (45 << 8))
#define MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE       (43 | (45 << 8))
#define MAP_ROUTE6_NORTH_ENTRANCE                 (44 | (45 << 8))
#define MAP_ROUTE7_EAST_ENTRANCE                  (45 | (45 << 8))
#define MAP_UNDERGROUND_PATH_WEST_ENTRANCE        (46 | (45 << 8))
#define MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL     (47 | (45 << 8))
#define MAP_UNDERGROUND_PATH_EAST_ENTRANCE        (48 | (45 << 8))
#define MAP_ROUTE8_WEST_ENTRANCE                  (49 | (45 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_1F             (50 | (45 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_2F             (51 | (45 << 8))
#define MAP_ROCK_TUNNEL_1F                        (52 | (45 << 8))
#define MAP_ROCK_TUNNEL_B1F                       (53 | (45 << 8))
#define MAP_POWER_PLANT                           (54 | (45 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_1F              (55 | (45 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_2F              (56 | (45 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_1F             (57 | (45 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_2F             (58 | (45 << 8))
#define MAP_ROUTE12_FISHING_HOUSE                 (59 | (45 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_1F              (60 | (45 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_2F              (61 | (45 << 8))
#define MAP_ROUTE16_HOUSE                         (62 | (45 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_1F             (63 | (45 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_2F             (64 | (45 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_1F              (65 | (45 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_2F              (66 | (45 << 8))
#define MAP_SEAFOM_ISLANDS_1F                     (67 | (45 << 8))
#define MAP_SEAFOAM_ISLANDS_B1F                   (68 | (45 << 8))
#define MAP_SEAFOAM_ISLANDS_B2F                   (69 | (45 << 8))
#define MAP_SEAFOAM_ISLANDS_B3F                   (70 | (45 << 8))
#define MAP_SEAFOAM_ISLANDS_B4F                   (71 | (45 << 8))
#define MAP_ROUTE22_NORTH_ENTRANCE                (72 | (45 << 8))
#define MAP_KANTO_VICTORY_ROAD_1F                 (73 | (45 << 8))
#define MAP_KANTO_VICTORY_ROAD_2F                 (74 | (45 << 8))
#define MAP_KANTO_VICTORY_ROAD_3F                 (75 | (45 << 8))
#define MAP_ROUTE25_SEA_COTTAGE                   (76 | (45 << 8))

// gMapGroup_OneIsland
#define MAP_ONE_ISLAND                       (0 | (46 << 8))
#define MAP_ONE_ISLAND_TREASURE_BEACH        (1 | (46 << 8))
#define MAP_ONE_ISLAND_KINDLE_ROAD           (2 | (46 << 8))
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F     (3 | (46 << 8))
#define MAP_ONE_ISLAND_POKEMON_CENTER_2F     (4 | (46 << 8))
#define MAP_ONE_ISLAND_HOUSE1                (5 | (46 << 8))
#define MAP_ONE_ISLAND_HOUSE2                (6 | (46 << 8))
#define MAP_ONE_ISLAND_HARBOR                (7 | (46 << 8))
#define MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA (8 | (46 << 8))
#define MAP_MT_EMBER_EXTERIOR                (9 | (46 << 8))
#define MAP_MT_EMBER_SUMMY_PATH_1F           (10 | (46 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_2F          (11 | (46 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_3F          (12 | (46 << 8))
#define MAP_MT_EMBER_SUMMIT                  (13 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_1F            (14 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F           (15 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F           (16 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B3F           (17 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B4F           (18 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B5F           (19 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS    (20 | (46 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS    (21 | (46 << 8))

// gMapGroup_TwoIsland
#define MAP_TWO_ISLAND                    (0 | (47 << 8))
#define MAP_TWO_ISLAND_HARBOR             (1 | (47 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F  (2 | (47 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_2F  (3 | (47 << 8))
#define MAP_TWO_ISLAND_HOUSE              (4 | (47 << 8))
#define MAP_TWO_ISLAND_JOYFUL_GAME_CORNER (5 | (47 << 8))
#define MAP_TWO_ISLAND_CAPE_BRINK         (6 | (47 << 8))
#define MAP_TWO_ISLAND_CAPE_BRINK_HOUSE   (7 | (47 << 8))

// gMapGroup_ThreeIsland
#define MAP_THREE_ISLAND                   (0 | (48 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F (1 | (48 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_2F (2 | (48 << 8))
#define MAP_THREE_ISLAND_HOUSE1            (3 | (48 << 8))
#define MAP_THREE_ISLAND_HOUSE2            (4 | (48 << 8))
#define MAP_THREE_ISLAND_HOUSE3            (5 | (48 << 8))
#define MAP_THREE_ISLAND_HOUSE4            (6 | (48 << 8))
#define MAP_THREE_ISLAND_HOUSE5            (7 | (48 << 8))
#define MAP_THREE_ISLAND_PORT              (8 | (48 << 8))
#define MAP_THREE_ISLAND_HARBOR            (9 | (48 << 8))
#define MAP_THREE_ISLAND_DUNSPARCE_TUNNEL  (10 | (48 << 8))
#define MAP_THREE_ISLAND_BOND_BRIDGE       (11 | (48 << 8))
#define MAP_THREE_ISLAND_BERRY_FOREST      (12 | (48 << 8))
#define MAP_THREE_ISLAND_MART              (13 | (48 << 8))

// gMapGroup_FourIsland
#define MAP_FOUR_ISLAND                       (0 | (49 << 8))
#define MAP_FOUR_ISLAND_HARBOR                (1 | (49 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F     (2 | (49 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_2F     (3 | (49 << 8))
#define MAP_FOUR_ISLAND_MART                  (4 | (49 << 8))
#define MAP_FOUR_ISLAND_POKEMON_DAY_CARE      (5 | (49 << 8))
#define MAP_FOUR_ISLAND_LORELEIS_HOUSE        (6 | (49 << 8))
#define MAP_FOUR_ISLAND_HOUSE1                (7 | (49 << 8))
#define MAP_FOUR_ISLAND_HOUSE2                (8 | (49 << 8))
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE (9 | (49 << 8))
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_1F       (10 | (49 << 8))
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F      (11 | (49 << 8))
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK     (12 | (49 << 8))

// gMapGroup_FiveIsland
#define MAP_FIVE_ISLAND                       (0 | (50 << 8))
#define MAP_FIVE_ISLAND_HARBOR                (1 | (50 << 8))
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F     (2 | (50 << 8))
#define MAP_FIVE_ISLAND_POKEMON_CENTER_2F     (3 | (50 << 8))
#define MAP_FIVE_ISLAND_HOUSE1                (4 | (50 << 8))
#define MAP_FIVE_ISLAND_HOUSE2                (5 | (50 << 8))
#define MAP_FIVE_ISLAND_WATER_LABYRINTH       (6 | (50 << 8))
#define MAP_FIVE_ISLAND_MEADOW                (7 | (50 << 8))
#define MAP_FIVE_ISLAND_ROCKET_WAREHOUSE      (8 | (50 << 8))
#define MAP_FIVE_ISLAND_MEMORIAL_PILLAR       (9 | (50 << 8))
#define MAP_FIVE_ISLAND_RESORT_GORGEOUS       (10 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE    (11 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM1       (12 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM2       (13 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM3       (14 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM4       (15 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM5       (16 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM6       (17 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM7       (18 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM8       (19 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM9       (20 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM10      (21 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM11      (22 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM12      (23 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM13      (24 | (50 << 8))
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM14      (25 | (50 << 8))
#define MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE (26 | (50 << 8))

// gMapGroup_SixIsland
#define MAP_SIX_ISLAND                           (0 | (51 << 8))
#define MAP_SIX_ISLAND_HARBOR                    (1 | (51 << 8))
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F         (2 | (51 << 8))
#define MAP_SIX_ISLAND_POKEMON_CENTER_2F         (3 | (51 << 8))
#define MAP_SIX_ISLAND_MART                      (4 | (51 << 8))
#define MAP_SIX_ISLAND_HOUSE                     (5 | (51 << 8))
#define MAP_SIX_ISLAND_WATER_PATH                (6 | (51 << 8))
#define MAP_SIX_ISLAND_WATER_PATH_HOUSE1         (7 | (51 << 8))
#define MAP_SIX_ISLAND_WATER_PATH_HOUSE2         (8 | (51 << 8))
#define MAP_SIX_ISLAND_GREEN_PATH                (9 | (51 << 8))
#define MAP_SIX_ISLAND_PATTERN_BUSH              (10 | (51 << 8))
#define MAP_SIX_ISLAND_OUTCAST_ISLAND            (11 | (51 << 8))
#define MAP_SIX_ISLAND_ALTERING_CAVE             (12 | (51 << 8))
#define MAP_SIX_ISLAND_RUIN_VALLEY               (13 | (51 << 8))
#define MAP_NEW_MAP2                             (14 | (51 << 8))
#define MAP_SIX_ISLAND_DOTTED_HOLE_B1F           (15 | (51 << 8))
#define MAP_SIX_ISLAND_DOTTED_HOLE_B2F           (16 | (51 << 8))
#define MAP_SIX_ISLAND_DOTTED_HOLE_B3F           (17 | (51 << 8))
#define MAP_SIX_ISLAND_DOTTED_HOLE_B4F           (18 | (51 << 8))
#define MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM (19 | (51 << 8))

// gMapGroup_SevenIsland
#define MAP_SEVEN_ISLAND                              (0 | (52 << 8))
#define MAP_SEVEN_ISLAND_HARBOR                       (1 | (52 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F            (2 | (52 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_2F            (3 | (52 << 8))
#define MAP_SEVEN_ISLAND_MART                         (4 | (52 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM1                  (5 | (52 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM2                  (6 | (52 << 8))
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE      (7 | (52 << 8))
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON               (8 | (52 << 8))
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY    (9 | (52 << 8))
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE         (10 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS                 (11 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER  (12 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER  (13 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER  (14 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER (15 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER  (16 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER    (17 | (52 << 8))
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER (18 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER                (19 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_LOBBY          (20 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_1F             (21 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_2F             (22 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_3F             (23 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_4F             (24 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_5F             (25 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_6F             (26 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_7F             (27 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_8F             (28 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_ROOF           (29 | (52 << 8))
#define MAP_SEVEN_ISLAND_TRAINER_TOWER_ELEVATOR       (30 | (52 << 8))

// gMapGroup_NewBarkTown
#define MAP_NEW_BARK_TOWN                    (0 | (53 << 8))
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_1F   (1 | (53 << 8))
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_2F   (2 | (53 << 8))
#define MAP_NEW_BARK_TOWN_HOUSE1             (3 | (53 << 8))
#define MAP_NEW_BARK_TOWN_ELMS_HOUSE         (4 | (53 << 8))
#define MAP_NEW_BARK_TOWN_PROFESSOR_ELMS_LAB (5 | (53 << 8))

// gMapGroup_CherrygroveCity
#define MAP_CHERRYGROVE_CITY                   (0 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_MART              (1 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_1F (2 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_2F (3 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE1            (4 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE2            (5 | (54 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE3            (6 | (54 << 8))

// gMapGroup_VioletCity
#define MAP_VIOLET_CITY                   (0 | (55 << 8))
#define MAP_VIOLET_CITY_HOUSE1            (1 | (55 << 8))
#define MAP_VIOLET_CITY_MART              (2 | (55 << 8))
#define MAP_VIOLET_CITY_GYM               (3 | (55 << 8))
#define MAP_VIOLET_CITY_EARLS_ACADEMY     (4 | (55 << 8))
#define MAP_VIOLET_CITY_POKEMON_CENTER_1F (5 | (55 << 8))
#define MAP_VIOLET_CITY_POKEMON_CENTER_2F (6 | (55 << 8))
#define MAP_VIOLET_CITY_HOUSE2            (7 | (55 << 8))
#define MAP_SPROUT_TOWER_1F               (8 | (55 << 8))
#define MAP_SPROUT_TOWER_2F               (9 | (55 << 8))
#define MAP_SPROUT_TOWER_3F               (10 | (55 << 8))

// gMapGroup_AzaleaTown
#define MAP_AZALEA_TOWN                   (0 | (56 << 8))
#define MAP_AZALEA_TOWN_MART              (1 | (56 << 8))
#define MAP_AZALEA_TOWN_POKEMON_CENTER_1F (2 | (56 << 8))
#define MAP_AZALEA_TOWN_POKEMON_CENTER_2F (3 | (56 << 8))
#define MAP_AZALEA_TOWN_KURTS_HOUSE       (4 | (56 << 8))
#define MAP_AZALEA_TOWN_GYM               (5 | (56 << 8))
#define MAP_AZALEA_TOWN_CHARCOAL_KILN     (6 | (56 << 8))
#define MAP_SLOWPOKE_WELL_B1F             (7 | (56 << 8))
#define MAP_SLOWPOKE_WELL_B2F             (8 | (56 << 8))
#define MAP_AZALEA_GATEHOUSE              (9 | (56 << 8))

// gMapGroup_GoldenrodCity
#define MAP_GOLDENROD_CITY                            (0 | (57 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_NORTH_ENTRANCE (1 | (57 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_SOUTH_ENTRANCE (2 | (57 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND                (3 | (57 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_B1F            (4 | (57 << 8))
#define MAP_GOLDEN_CITY_UNDERGROUND_WAREHOUSE         (5 | (57 << 8))
#define MAP_GOLDENROD_CITY_GYM                        (6 | (57 << 8))
#define MAP_GOLDENROD_CITY_FLOWER_SHOP                (7 | (57 << 8))
#define MAP_GOLDENROD_CITY_NAME_RATERS_HOUSE          (8 | (57 << 8))
#define MAP_GOLDENROD_CITY_HOUSE1                     (9 | (57 << 8))
#define MAP_GOLDENROD_CITY_HOUSE2                     (10 | (57 << 8))
#define MAP_GOLDENROD_CITY_GAME_CORNER                (11 | (57 << 8))
#define MAP_GOLDENROD_CITY_BILLS_FAMILYS_HOUSE        (12 | (57 << 8))
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_1F          (13 | (57 << 8))
#define MAP_GOLDENROD_CITY_GATEHOUSE_NORTH            (14 | (57 << 8))
#define MAP_GOLDENROD_CITY_MAGNET_TRAIN_STATION       (15 | (57 << 8))
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_2F          (16 | (57 << 8))
#define MAP_GOLDENROD_CITY_BIKE_SHOP                  (17 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_1F        (18 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_2F        (19 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_3F        (20 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_4F        (21 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_5F        (22 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_6F        (23 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_ROOFTOP   (24 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_ELEVATOR  (25 | (57 << 8))
#define MAP_GOLDENROD_CITY_DEPARTMENT_STORE_B1F       (26 | (57 << 8))
#define MAP_GOLDENROD_CITY_RADIO_TOWER_1F             (27 | (57 << 8))
#define MAP_GOLDENROD_CITY_RADIO_TOWER_2F             (28 | (57 << 8))
#define MAP_GOLDENROD_CITY_RADIO_TOWER_3F             (29 | (57 << 8))
#define MAP_GOLDENROD_CITY_RADIO_TOWER_4F             (30 | (57 << 8))
#define MAP_GOLDENROD_CITY_RADIO_TOWER_5F             (31 | (57 << 8))

// gMapGroup_EcruteakCity
#define MAP_ECRUTEAK_CITY                   (0 | (58 << 8))
#define MAP_ECRUTEAK_CITY_GATEHOUSE_WEST    (1 | (58 << 8))
#define MAP_ECRUTEAK_CITY_GATEHOUSE_EAST    (2 | (58 << 8))
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_1F (3 | (58 << 8))
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_2F (4 | (58 << 8))
#define MAP_ECRUTEAK_CITY_MART              (5 | (58 << 8))
#define MAP_TIN_TOWER_1F                    (6 | (58 << 8))
#define MAP_TIN_TOWER_2F                    (7 | (58 << 8))
#define MAP_TIN_TOWER_3F                    (8 | (58 << 8))
#define MAP_TIN_TOWER_4F                    (9 | (58 << 8))
#define MAP_TIN_TOWER_5F                    (10 | (58 << 8))
#define MAP_TIN_TOWER_6F                    (11 | (58 << 8))
#define MAP_TIN_TOWER_7F                    (12 | (58 << 8))
#define MAP_TIN_TOWER_8F                    (13 | (58 << 8))
#define MAP_TIN_TOWER_9F                    (14 | (58 << 8))
#define MAP_TIN_TOWER_10F                   (15 | (58 << 8))
#define MAP_ECRUTEAK_CITY_GYM               (16 | (58 << 8))
#define MAP_BARRIER_STATION_NORTH_ENTRANCE  (17 | (58 << 8))
#define MAP_BARRIER_STATION_SOUTH           (18 | (58 << 8))
#define MAP_BARRIER_STATION_NORTH           (19 | (58 << 8))
#define MAP_BURNED_TOWER_1F                 (20 | (58 << 8))
#define MAP_BURNED_TOWER_B1F                (21 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE1            (22 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE2            (23 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE3            (24 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE4            (25 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE5            (26 | (58 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE6            (27 | (58 << 8))
#define MAP_ECRUTEAK_CITY_DANCE_THEATER     (28 | (58 << 8))

// gMapGroup_OlivineCity
#define MAP_OLIVINE_CITY                   (0 | (59 << 8))
#define MAP_OLIVINE_CITY_HARBOR            (1 | (59 << 8))
#define MAP_OLIVINE_CITY_POKEMON_CENTER_1F (2 | (59 << 8))
#define MAP_OLIVINE_CITY_POKEMON_CENTER_2F (3 | (59 << 8))
#define MAP_OLIVINE_CITY_MART              (4 | (59 << 8))
#define MAP_OLIVINE_CITY_GYM               (5 | (59 << 8))
#define MAP_OLIVINE_CITY_HOUSE1            (6 | (59 << 8))
#define MAP_OLIVINE_CITY_HOUSE2            (7 | (59 << 8))
#define MAP_OLIVINE_CITY_HOUSE3            (8 | (59 << 8))
#define MAP_OLIVINE_CITY_CAFE              (9 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_1F     (10 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_2F     (11 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_3F     (12 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_4F     (13 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_5F     (14 | (59 << 8))
#define MAP_OLIVINE_CITY_LIGHTHOUSE_6F     (15 | (59 << 8))

// gMapGroup_CianwoodCity
#define MAP_CIANWOOD_CITY                   (0 | (60 << 8))
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_1F (1 | (60 << 8))
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_2F (2 | (60 << 8))
#define MAP_CIANWOOD_CITY_GYM               (3 | (60 << 8))
#define MAP_CIANWOOD_CITY_KIRKS_HOUSE       (4 | (60 << 8))
#define MAP_CIANWOOD_CITY_PHOTO_STUDIO      (5 | (60 << 8))
#define MAP_CIANWOOD_CITY_HOUSE1            (6 | (60 << 8))
#define MAP_CIANWOOD_CITY_HOUSE2            (7 | (60 << 8))

// gMapGroup_MahoganyTown
#define MAP_MAHOGANY_TOWN                    (0 | (61 << 8))
#define MAP_MAHOGANY_TOWN_GATEHOUSE          (1 | (61 << 8))
#define MAP_MAHOGANY_TOWN_ROCKET_HIDEOUT_1F  (2 | (61 << 8))
#define MAP_MAHOGANY_TOWN_ROCKET_HIDEOUT_B1F (3 | (61 << 8))
#define MAP_MAHOGANY_TOWN_ROCKET_HIDEOUT_B2F (4 | (61 << 8))
#define MAP_MAHOGANY_TOWN_ROCKET_HIDEOUT_B3F (5 | (61 << 8))
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_1F  (6 | (61 << 8))
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_2F  (7 | (61 << 8))
#define MAP_MAHOGANY_TOWN_GYM                (8 | (61 << 8))
#define MAP_MAHOGANY_TOWN_HOUSE              (9 | (61 << 8))

// gMapGroup_BlackthornCity
#define MAP_BLACKTHORN_CITY                     (0 | (62 << 8))
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_1F   (1 | (62 << 8))
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_2F   (2 | (62 << 8))
#define MAP_BLACKTHORN_CITY_MART                (3 | (62 << 8))
#define MAP_BLACKTHORN_CITY_MOVE_DELETERS_HOUSE (4 | (62 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE1              (5 | (62 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE2              (6 | (62 << 8))
#define MAP_BLACKTHORN_CITY_GYM                 (7 | (62 << 8))
#define MAP_BLACKTHORN_CITY_GYM_2F              (8 | (62 << 8))
#define MAP_DRAGONS_DEN_ENTRANCE                (9 | (62 << 8))
#define MAP_DRAGONS_DEN_B1F                     (10 | (62 << 8))
#define MAP_DRAGONS_DEN_B2F                     (11 | (62 << 8))
#define MAP_DRAGONS_DEN_HOUSE                   (12 | (62 << 8))

// gMapGroup_JohtoRoutes
#define MAP_ROUTE26 (0 | (63 << 8))
#define MAP_ROUTE27 (1 | (63 << 8))
#define MAP_ROUTE28 (2 | (63 << 8))
#define MAP_ROUTE29 (3 | (63 << 8))
#define MAP_ROUTE30 (4 | (63 << 8))
#define MAP_ROUTE31 (5 | (63 << 8))
#define MAP_ROUTE32 (6 | (63 << 8))
#define MAP_ROUTE33 (7 | (63 << 8))
#define MAP_ROUTE34 (8 | (63 << 8))
#define MAP_ROUTE35 (9 | (63 << 8))
#define MAP_ROUTE36 (10 | (63 << 8))
#define MAP_ROUTE37 (11 | (63 << 8))
#define MAP_ROUTE38 (12 | (63 << 8))
#define MAP_ROUTE39 (13 | (63 << 8))
#define MAP_ROUTE40 (14 | (63 << 8))
#define MAP_ROUTE41 (15 | (63 << 8))
#define MAP_ROUTE42 (16 | (63 << 8))
#define MAP_ROUTE43 (17 | (63 << 8))
#define MAP_ROUTE44 (18 | (63 << 8))
#define MAP_ROUTE45 (19 | (63 << 8))
#define MAP_ROUTE46 (20 | (63 << 8))

// gMapGroup_JohtoDungeons
#define MAP_UNION_CAVE_1F        (0 | (64 << 8))
#define MAP_UNION_CAVE_B1F       (1 | (64 << 8))
#define MAP_UNION_CAVE_B2F       (2 | (64 << 8))
#define MAP_ILEX_FOREST          (3 | (64 << 8))
#define MAP_DARK_CAVE_VIOLET     (4 | (64 << 8))
#define MAP_DARK_CAVE_BLACKTHORN (5 | (64 << 8))
#define MAP_TOHJO_FALLS          (6 | (64 << 8))
#define MAP_MT_MORTAR_ENTRANCE   (7 | (64 << 8))
#define MAP_MT_MORTAR_1F         (8 | (64 << 8))
#define MAP_MT_MORTAR_2F         (9 | (64 << 8))
#define MAP_MT_MORTAR_B1F        (10 | (64 << 8))
#define MAP_ICE_PATH             (11 | (64 << 8))
#define MAP_ICE_PATH_B1F         (12 | (64 << 8))
#define MAP_ICE_PATH_B1F_2       (13 | (64 << 8))
#define MAP_ICE_PATH_B2F         (14 | (64 << 8))
#define MAP_ICE_PATH_B2F_2       (15 | (64 << 8))
#define MAP_ICE_PATH_B3F         (16 | (64 << 8))
#define MAP_MT_SILVER_ENTRANCE   (17 | (64 << 8))
#define MAP_MT_SILVER_MAIN_ROOM  (18 | (64 << 8))
#define MAP_MT_SILVER_SOUTH_ROOM (19 | (64 << 8))
#define MAP_MT_SILVER_NORTH_ROOM (20 | (64 << 8))
#define MAP_MT_SILVER_BOSS_ROOM  (21 | (64 << 8))

// gMapGroup_IndoorRoute26
#define MAP_ROUTE26_GATEHOUSE (0 | (65 << 8))
#define MAP_ROUTE26_HOUSE1    (1 | (65 << 8))
#define MAP_ROUTE26_HOUSE2    (2 | (65 << 8))

// gMapGroup_IndoorRoute27
#define MAP_ROUTE27_HOUSE (0 | (66 << 8))

// gMapGroup_IndoorRoute28
#define MAP_ROUTE28_POKEMON_CENTER_1F (0 | (67 << 8))
#define MAP_ROUTE28_POKEMON_CENTER_2F (1 | (67 << 8))
#define MAP_ROUTE28_HOUSE             (2 | (67 << 8))

// gMapGroup_IndoorRoute29
#define MAP_ROUTE29_GATEHOUSE (0 | (68 << 8))

// gMapGroup_IndoorRoute30
#define MAP_ROUTE30_HOUSE1            (0 | (69 << 8))
#define MAP_ROUTE30_MR_POKEMONS_HOUSE (1 | (69 << 8))

// gMapGroup_IndoorRoute31
#define MAP_ROUTE31_GATEHOUSE (0 | (70 << 8))

// gMapGroup_IndoorRoute32
#define MAP_ROUTE32_GATEHOUSE         (0 | (71 << 8))
#define MAP_ROUTE32_POKEMON_CENTER_1F (1 | (71 << 8))
#define MAP_ROUTE32_POKEMON_CENTER_2F (2 | (71 << 8))

// gMapGroup_IndoorRoute34
#define MAP_ROUTE34_GATEHOUSE        (0 | (72 << 8))
#define MAP_ROUTE34_POKEMON_DAY_CARE (1 | (72 << 8))

// gMapGroup_IndoorRoute36
#define MAP_ROUTE36_GATEHOUSE (0 | (73 << 8))

// gMapGroup_IndoorRoute39
#define MAP_MOO_MOO_FARM      (0 | (74 << 8))
#define MAP_MOO_MOO_FARM_BARN (1 | (74 << 8))

// gMapGroup_IndoorRoute43
#define MAP_ROUTE43_GATEHOUSE (0 | (75 << 8))

// gMapGroup_RuinsOfAlph
#define MAP_RUINS_OF_ALPH_OUTSIDE              (0 | (76 << 8))
#define MAP_RUINS_OF_ALPH_RESEARCH_CENTER      (1 | (76 << 8))
#define MAP_RUINS_OF_ALPH_INNER_CHAMBER        (2 | (76 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_CHAMBER       (3 | (76 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_ITEM_ROOM     (4 | (76 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_WORD_ROOM     (5 | (76 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_CHAMBER        (6 | (76 << 8))
#define MAP_RUINS_OF_ALPH_HO_OK_ITEM_ROOM      (7 | (76 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_WORD_ROOM      (8 | (76 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_CHAMBER      (9 | (76 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_ITEM_ROOM    (10 | (76 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_WORD_ROOM    (11 | (76 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_CHAMBER   (12 | (76 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM (13 | (76 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_WORD_ROOM (14 | (76 << 8))

// gMapGroup_NationalPark
#define MAP_NATIONAL_PARK                 (0 | (77 << 8))
#define MAP_NATIONAL_PARK_GATEHOUSE_SOUTH (1 | (77 << 8))
#define MAP_NATIONAL_PARK_GATEHOUSE_EAST  (2 | (77 << 8))

// gMapGroup_BattleTower
#define MAP_BATTLE_TOWER_GATEHOUSE   (0 | (78 << 8))
#define MAP_BATTLE_TOWER_OUTSIDE     (1 | (78 << 8))
#define MAP_BATTLE_TOWER_LOBBY       (2 | (78 << 8))
#define MAP_BATTLE_TOWER_ELEVATOR    (3 | (78 << 8))
#define MAP_BATTLE_TOWER_CORRIDOR    (4 | (78 << 8))
#define MAP_BATTLE_TOWER_BATTLE_ROOM (5 | (78 << 8))

// gMapGroup_WhirlIslands
#define MAP_WHIRL_ISLANDS_NORTH_WEST_ENTRANCE (0 | (79 << 8))
#define MAP_WHIRL_ISLANDS_NORTH_EAST_ENTRANCE (1 | (79 << 8))
#define MAP_WHIRL_ISLANDS_SOUTH_WEST_ENTRANCE (2 | (79 << 8))
#define MAP_WHIRL_ISLANDS_SOUTH_EAST_ENTRANCE (3 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B2F                 (4 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B3F                 (5 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B4F                 (6 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B5F                 (7 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B6F                 (8 | (79 << 8))
#define MAP_WHIRL_ISLANDS_B7F                 (9 | (79 << 8))

// gMapGroup_LakeOfRage
#define MAP_LAKE_OF_RAGE        (0 | (80 << 8))
#define MAP_LAKE_OF_RAGE_HOUSE1 (1 | (80 << 8))
#define MAP_LAKE_OF_RAGE_HOUSE2 (2 | (80 << 8))

#define MAP_GROUPS_COUNT 81

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
